#ifndef NAMMA_AUTOSAR_LIN_CFG_H
#define NAMMA_AUTOSAR_LIN_CFG_H

// This file is autogenerated, any hand modifications will be lost!

#include <Platform_Types.h>

#define LIN_DRIVER_MAX_CHANNEL    (2)


typedef struct {
    uint8 lin_index;
    boolean lin_dev_error_detect;
    boolean lin_version_info_api;
    uint16 lin_timeout_sec;
} LinGeneralCfgType;


typedef enum {
    MASTER,
    SLAVE
} LinNodeType;


typedef struct {
    uint16 lin_chan_id;
    uint16 lin_chan_baudrate;
    LinNodeType lin_node_type;
    boolean lin_wakeup_support;
    const char* lin_wakeup_source;
    const char* lin_clock_ref;
} LinChannelCfgType;


typedef struct {
    const LinGeneralCfgType general;
    const LinChannelCfgType chn_cfg;
} Lin_ConfigType;



extern const Lin_ConfigType LinConfigs[LIN_DRIVER_MAX_CHANNEL];


#endif
