#include <stddef.h>
#include <Lin_cfg.h>


// This file is autogenerated, any hand modifications will be lost!



const Lin_ConfigType LinConfigs[LIN_DRIVER_MAX_CHANNEL] = {
	{
		/* Lin channel - 0 */
		.general = {
			.lin_index = 0,
			.lin_dev_error_detect = FALSE,
			.lin_version_info_api = FALSE,
			.lin_timeout_sec = 2
		},
		.chn_cfg = {
			.lin_chan_id = 0,
			.lin_chan_baudrate = 1000,
			.lin_node_type = SLAVE,
			.lin_wakeup_support = FALSE,
			.lin_wakeup_source = "test", /* This could be wrong! */
			.lin_clock_ref = "test", /* This could be wrong! */ 
		}
	},
	{
		/* Lin channel - 1 */
		.general = {
			.lin_index = 1,
			.lin_dev_error_detect = TRUE,
			.lin_version_info_api = TRUE,
			.lin_timeout_sec = 0
		},
		.chn_cfg = {
			.lin_chan_id = 1,
			.lin_chan_baudrate = 1000,
			.lin_node_type = MASTER,
			.lin_wakeup_support = FALSE,
			.lin_wakeup_source = "chumma", /* This could be wrong! */
			.lin_clock_ref = "chumma", /* This could be wrong! */ 
		}
	},
};
